#@ load("@ytt:data", "data")
#@ if hasattr(data.values.env.init, "sealed_secrets"):
  #@ for ss in data.values.env.init.sealed_secrets:
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: #@ ss.sync_wave
    sealedsecrets.bitnami.com/cluster-wide: #@ ss.cluster_wide
  name: #@ ss.name
  namespace: #@ data.values.env.cluster + "-" + data.values.env.pfops.env
spec:
  encryptedData: #@ ss.encryptedData
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: #@ ss.sync_wave
        sealedsecrets.bitnami.com/cluster-wide: #@ ss.cluster_wide
      name: #@ ss.name
      namespace: #@ data.values.env.cluster + "-" + data.values.env.pfops.env
    type: #@ ss.type
  #@ end
#@ end
