apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pfops-cm-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: pfops-cm-plugin
    spec:
      version: v1.0
      generate:
          command: ["/bin/sh"]
          args: ['cm-generator.sh']
      discover:
        find:
          command: [sh, -c, find . -name cm-generator.sh]

---

apiVersion: v1
kind: Secret
metadata:
  name: pfops-reg
  namespace: argocd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8vdjEvIjp7InVzZXJuYW1lIjoic2lhdmFzaGdoZjIwMDAiLCJwYXNzd29yZCI6InNpYTEzNTc5In19fQ==

---

apiVersion: v1
kind: Secret
metadata:
  name: ssh-wsl
  namespace: argocd
type: kubernetes.io/ssh-auth
data:
  ssh-publickey: >-
    c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUJ1K2tMSG5rWEE2cUIrSVNXbnBKaXBMblJTb2FzbEwxUFBrQ1BxdlVVQ2Qgc2lhLmdmYXJkLmNvZGVAZ21haWwuY29tCg==
  ssh-privatekey: >-
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBYnZwQ3g1NUZ3T3FnZmlFbHA2U1lxUzUwVXFHckpTOVR6NUFqNnIxRkFuUUFBQUtDa21rVUtwSnBGCkNnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQWJ2cEN4NTVGd09xZ2ZpRWxwNlNZcVM1MFVxR3JKUzlUejVBajZyMUZBblEKQUFBRUNEMEs5V3Z3eWQrd1lYYVlvK0ltOS9HdS9NNXBaOFRYVTQySE1CT2xQd1lSdStrTEhua1hBNnFCK0lTV25wSmlwTApuUlNvYXNsTDFQUGtDUHF2VVVDZEFBQUFHSE5wWVM1blptRnlaQzVqYjJSbFFHZHRZV2xzTG1OdmJRRUNBd1FGCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQ==
