apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pfops-cm-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: pfops-cm-plugin
    spec:
      version: v1.0
      generate:
          command: ["/bin/sh"]
          args: ['cm-generator.sh']
      discover:
        find:
          command: [sh, -c, find . -name cm-generator.sh]

apiVersion: v1
kind: Secret
metadata:
  name: pfops-reg
  namespace: argocd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8vdjEvIjp7InVzZXJuYW1lIjoic2lhdmFzaGdoZjIwMDAiLCJwYXNzd29yZCI6InNpYTEzNTc5In19fQ==