#@ load("@ytt:data", "data")
#@ for hook in dir(data.values.app.resources):
  #@ for rsc in dir(data.values.app.resources[hook]):
    #@ if rsc == "secrets":
      #@ for secret in data.values.app.resources[hook][rsc]:
---
apiVersion: v1
data: #@ secret.data
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: #@ secret.sync_wave
  name: #@ secret.name
  #@ if data.values.app.override_na == "true":
    #@ namespace = secret.ns
  #@ elif data.values.app.default_ns == "true":
    #@ namespace = data.values.app.cluster + "-" + data.values.app.env
  #@ else :
    #@ namespace = data.values.app.cluster + "-" + data.values.app.env + "-" + secret.ns
  #@ end
  namespace: #@ namespace
type: #@ secret.type

      #@ end
    #@ end
  #@ end
#@ end