#@ load("@ytt:data", "data")
#@ for hook in dir(data.values.app.resources):
  #@ for rsc in dir(data.values.app.resources[hook]):
    #@ if rsc == "secret_stores":
      #@ for ss in data.values.app.resources[hook][rsc]:
---
apiVersion: external-secrets.io/v1beta1
kind: #@ ss.kind
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: #@ ss.sync_wave
    #@ if/end hook != "Sync":
    argocd.argoproj.io/hook: #@ hook
  name: #@ ss.name
  #@ if data.values.app.override_na == "true":
    #@ namespace = ss.ns
  #@ elif data.values.app.default_ns == "true":
    #@ namespace = data.values.app.cluster + "-" + data.values.app.env
  #@ else :
    #@ namespace = data.values.app.cluster + "-" + data.values.app.env + "-" + ss.ns
  #@ end
  namespace: #@ namespace
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: #@ ss.sa.name
            namespace: #@ ss.sa.ns
      region: #@ ss.region
      service: #@ ss.service
      #@ end
    #@ end
  #@ end
#@ end
