#@ load("@ytt:data", "data")
#@ for hook in dir(data.values.app.resources):
  #@ for rsc in dir(data.values.app.resources[hook]):
    #@ if rsc == "secrets":
      #@ for secret in data.values.app.resources[hook][rsc]:
---
apiVersion: v1
#@ if hasattr(secret, "data"):
data: #@ secret.data
#@ end 
kind: Secret
metadata:
  #@ if hasattr(secret, "annotations"):
  annotations: #@ secret.annotations
  #@ end 
  name: #@ secret.name
  #@ if data.values.app.override_na == "true":
    #@ namespace = secret.ns
  #@ elif data.values.app.default_ns == "true":
    #@ namespace = data.values.app.cluster + "-" + data.values.app.env
  #@ else :
    #@ namespace = data.values.app.cluster + "-" + data.values.app.env + "-" + secret.ns
  #@ end
  namespace: #@ namespace
type: #@ secret.type

      #@ end
    #@ end
  #@ end
#@ end