#@ load("@ytt:data", "data")

#@ for hook in dir(data.values.app.resources):
  #@ for rsc in dir(data.values.app.resources[hook]):
    #@ if rsc == "serviceacounts":
      #@ for sa in data.values.app.resources[hook][rsc]:
---

apiVersion: v1
kind: ServiceAccount
metadata:
  #@ if data.values.app.override_na == "true":
    #@ namespace = sa.ns
  #@ elif data.values.app.default_ns == "true":
    #@ namespace = data.values.app.cluster + "-" + data.values.app.env
  #@ else :
    #@ namespace = data.values.app.cluster + "-" + data.values.app.env + "-" + sa.ns
  #@ end
  namespace: #@ namespace
  name: #@ sa.name
  annotations:
    argocd.argoproj.io/sync-wave: #@ sa.sync_wave
    #@ if/end hook != "Sync":
    argocd.argoproj.io/hook: #@ hook
#@ if/end hasattr(sa, "automountServiceAccountToken"):
automountServiceAccountToken: #@ sa.automountServiceAccountToken

      #@ end
    #@ end
  #@ end
#@ end
